src/Web.Client/Models/Music.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyMusicMVC
{
    public class Music
    {
        public int Id { get; set; }

        public String Name { get; set; }

        public int ArtistId { get; set; }

        public Artist Artist { get; set; }
    }
}

src/Web.Client/ViewModels/MusicViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyMusicMVC
{
    public class MusicViewModel
    {
        public string MusicId { get; set; }

        public Music Music { get; set; }

        public SelectList ArtistList { get; set; }

        [Required(ErrorMessage = "Please enter the Artist")]
        [Display(Name = "Artist")]
        public string ArtistId { get; set; }
    }
}

src/Web.Client/Controllers/MusicController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace MyMusicMVC.Controllers
{
    public class MusicController : Controller
    {
        #region Properties & Constructors
        private readonly IConfiguration _config;

        private string BaseURL
        {
            get
            {
                return _config.GetSection("BaseURL").GetSection("URL").Value;
            }
        }

        public MusicController(IConfiguration config)
        {
            _config = config;
        }
        #endregion

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddMusic()
        {
            var musicViewModel = new MusicViewModel();
            List<Artist> artistList = new List<Artist>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{BaseURL}Artist/Artists"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    artistList = JsonConvert.DeserializeObject<List<Artist>>(apiResponse);
                }
            }

            musicViewModel.ArtistList = new SelectList(artistList, "Id", "Name");

            return View(musicViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddMusic(MusicViewModel musicViewModel)
        {
            if (ModelState.IsValid)
            {
                using (var httpClient = new HttpClient())
                {
                    var music = new Music()
                    {
                        ArtistId = int.Parse(musicViewModel.ArtistId),
                        Name = musicViewModel.Music.Name
                    };

                    // Verify athentication
                    string tokenJwt = HttpContext.Session.GetString("token");
                    if (string.IsNullOrEmpty(tokenJwt))
                    {
                        ViewBag.ErrorMessage = "You must be authenticate";
                        return View(musicViewModel);
                    }

                    var stringData = JsonConvert.SerializeObject(music);
                    var contentData = new StringContent(stringData, Encoding.UTF8, "application/json");

                    // Token in Header
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("bearer", tokenJwt);

                    var response = await httpClient.PostAsync($"{BaseURL}Music/CreateMusic", contentData);

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    ViewBag.ErrorMessage = response.ReasonPhrase;

                    return View(musicViewModel);
                }
            }

            return View(musicViewModel);
        }
    }
}

src/Web.Client/Views/Music/AddMusic.cshtml
@model MusicViewModel

<span class="btn-danger">@ViewBag.ErrorMessage</span>
<form asp-controller="Music" asp-action="AddMusic" method="post" class="col-12 form-horizontal" role="form">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="@Model.Music.Name" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="@Model.Music.Name" class="form-control" />
            <span asp-validation-for="@Model.Music.Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="@Model.ArtistId" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <select asp-for="@Model.ArtistId" asp-items="@Model.ArtistList" class="form-group col-5 btn btn-primary">
                <option value="-1">Select Artist</option>
            </select>
            <span asp-validation-for="@Model.ArtistId" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Add Music" />
        </div>
    </div>
</form>